djangoShop/urls.py
from django.contrib import admin
from rest_framework.authtoken import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.views import RedirectToMainView
from rest.views import CustomAuthToken

urlpatterns = [
    path("myuser/", include("myuser.urls", namespace="myuser")),
    path('admin/', admin.site.urls),
    path("shop/", include("shop.urls", namespace="shop")),
    path("rest/", include("rest.urls")),
    path('api-etoken-auth/', CustomAuthToken.as_view()),
    path("", RedirectToMainView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest/urls.py
from .API.resources import ProductViewSet, OrderViewSet, ReturnViewSet
from rest_framework import routers


router = routers.SimpleRouter()
router.register(r'products', ProductViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'returns', ReturnViewSet)
urlpatterns = router.urls

shop/urls.py
from django.urls import path
from .views import ProductList, MainView, OrderList, ReturnSuccessView, \
    UpdateProductView, ReturnList, CreateProductView, CreateOrder, CreateReturn, DeleteReturn, CeleryReturnView


app_name = "shop"

urlpatterns = [
    path("main", MainView.as_view(), name="main"),
    path("product_list", ProductList.as_view(), name="product_list"),
    path("orders", OrderList.as_view(), name="orders"),
    path("return_success", ReturnSuccessView.as_view(), name="return_success"),
    path("update_product/<int:pk>", UpdateProductView.as_view(), name="update_product"),
    path("return_list", ReturnList.as_view(), name="return_list"),
    path("add_product", CreateProductView.as_view(), name="add_product"),
    path("create_order", CreateOrder.as_view(), name="create_order"),
    path("create_return", CreateReturn.as_view(), name="create_return"),
    path("delete_return/<int:pk>", DeleteReturn.as_view(), name="delete_return"),
    path("aprrove_all_returns/", CeleryReturnView.as_view(), name="approve_all_returns"),
]

shop/models.py
from django.db import models
from myuser.models import MyUser
from .exceptions import NotEnoughMoneyException, NotEnoughProductException, ReturnAlreadyExists, ReturnTimeExpired
from datetime import timedelta
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.IntegerField(default=0)
    photo = models.ImageField(upload_to="products", blank=True, null=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name="orders")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="orders")
    amount = models.IntegerField()
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["create_date"]

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.product.amount < self.amount:
            raise NotEnoughProductException
        elif self.total_cost > self.user.wallet:
            raise NotEnoughMoneyException
        self.user.wallet -= self.total_cost
        self.product.amount -= self.amount
        self.user.save()
        self.product.save()
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    def delete(self, using=None, keep_parents=False):
        self.user.wallet += self.total_cost
        self.product.amount += self.amount
        self.user.save()
        self.product.save()
        super().delete(using=None, keep_parents=False)

    @property
    def total_cost(self):
        return self.amount * self.product.cost


class Return(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ["create_date"]

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if timezone.now() > self.order.create_date + timedelta(minutes=3):
            raise ReturnTimeExpired
        elif Return.objects.filter(order=self.order).exists():
            raise ReturnAlreadyExists
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    def delete(self, using=None, keep_parents=False, approved=False):
        if approved:
            self.order.delete()
        super().delete(using=None, keep_parents=False)

shop/forms.py
from django.forms import ModelForm, ImageField
from django.forms import ValidationError
from .models import Order, Return, Product
from django.forms import HiddenInput


class OrderForm(ModelForm):
    class Meta:
        fields = ["user", "product", "amount"]
        model = Order
        widgets = {'user': HiddenInput(),
                   'product': HiddenInput()}

    def clean_amount(self):
        amount = self.cleaned_data.get("amount")
        self.product = self.cleaned_data.get("product")
        self.user = self.cleaned_data.get("user")
        if amount <= 0:
            raise ValidationError("Invalid amount")
        return amount


class ReturnForm(ModelForm):

    class Meta:
        fields = ["order"]
        model = Return
        widgets = {
            "order": HiddenInput()
        }


class CreateUpdateProductForm(ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        cost = cleaned_data.get("cost")
        amount = cleaned_data.get("amount")
        if amount <= 0:
            self.add_error("amount", "Invalid amount")
        if cost <= 0:
            self.add_error("cost", "Invalid cost")

    class Meta:
        model = Product
        fields = ("name", "description", "cost", "amount", "photo")

shop/views.py
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, RedirectView, DeleteView, View
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from .models import Product, Order, Return
from .forms import OrderForm, ReturnForm, CreateUpdateProductForm
from myuser.misc import SuperUserRequired
from .exceptions import NotEnoughMoneyException, NotEnoughProductException, ReturnAlreadyExists, ReturnTimeExpired
from django.contrib import messages
from shop.tasks import approve_all_returns
from django.shortcuts import render


class MainView(TemplateView):
    template_name = "main.html"


class ProductList(ListView):
    template_name = "product_list.html"
    model = Product
    extra_context = {"empty_form": OrderForm()}
    paginate_by = 3


class CreateOrder(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('shop:product_list')

    def form_valid(self, form):
        try:
            self.object = form.save()
        except NotEnoughProductException:
            messages.add_message(self.request, messages.ERROR, "Not enough product")
        except NotEnoughMoneyException:
            messages.add_message(self.request, messages.ERROR, "Not enough money")
        else:
            messages.add_message(self.request, messages.SUCCESS, "Order created")
            return HttpResponseRedirect(self.get_success_url())
        return redirect(reverse("shop:product_list"))

    def form_invalid(self, form):
        return redirect(reverse("shop:product_list"))


class OrderList(ListView):
    template_name = "order_list.html"
    model = Order
    paginate_by = 3
    extra_context = {"form": ReturnForm}


class CreateReturn(CreateView):
    model = Return
    form_class = ReturnForm
    success_url = reverse_lazy('shop:orders')

    def form_valid(self, form):
        try:
            self.object = form.save()
        except ReturnTimeExpired:
            messages.add_message(self.request, messages.ERROR, "Return time expired")
        except ReturnAlreadyExists:
            messages.add_message(self.request, messages.ERROR, "Return already exists")
        else:
            messages.add_message(self.request, messages.SUCCESS, "Return has been requested")
        return redirect(reverse("shop:orders"))

    def form_invalid(self, form):
        return redirect(reverse("shop:orders"))


class ReturnSuccessView(TemplateView):
    template_name = "return_success.html"


class UpdateProductView(SuperUserRequired, UpdateView):
    model = Product
    form_class = CreateUpdateProductForm
    template_name = "product_update.html"
    success_url = reverse_lazy("shop:product_list")


class CreateProductView(SuperUserRequired, CreateView):
    model = Product
    form_class = CreateUpdateProductForm
    template_name = "product_add.html"
    success_url = reverse_lazy("shop:product_list")


class ReturnList(SuperUserRequired, ListView):
    template_name = "return_list.html"
    model = Return
    paginate_by = 3


class DeleteReturn(DeleteView):
    success_url = reverse_lazy("shop:return_list")
    model = Return

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        approve = request.POST.get("approve", False)
        self.object.delete(approved=approve)
        if approve:
            messages.add_message(request, messages.SUCCESS, "Return was approved")
        else:
            messages.add_message(request, messages.SUCCESS, "Return was discarded")
        return HttpResponseRedirect(success_url)


class RedirectToMainView(RedirectView):
    url = reverse_lazy("shop:main")


class CeleryReturnView(SuperUserRequired, View):

    def post(self, request, *args, **kwargs):
        approve_all_returns.delay()
        return render(request, "return_approved.html", {})

shop/templates/main.html
{% extends "base.html" %}
{% block title %} Main {% endblock %}

{% block content %}
    <h1>Welcome to main page</h1>
    <p><a href="{% url 'shop:product_list' %}">Product list</a></p>
    {% include "user.html" %}

{% endblock %}

shop/templates/order_list.html
{% extends "base.html" %}
{% block title %} Orders list {% endblock %}

{% block content %}
    {% include "user.html" %}
<h2>Order list</h2>
    <table border="1">
    <tr>
        <td>id</td>
        <td>Product</td>
        <td>Amount</td>
        <td>Date</td>
        <td>Total cost</td>
    </tr>
{% for elem in object_list %}
    <tr>
        <td>{{ elem.id }}</td>
        <td>Product: {{ elem.product }}</td>
        <td>Amount: {{ elem.amount }}</td>
        <td>Date: {{ elem.create_date }}</td>
        <td>Total cost: {{ elem.total_cost }}</td>

        <td><form method="post" action="{% url 'shop:create_return' %}">
                {% csrf_token %}
            {% if elem.id == invalid_form_number %}
                    {{ error_form.as_p }}
                    {% else %}
                {{ form.as_p }}
                {% endif %}
                <input name="order" type="hidden" value="{{ elem.id }}">
                <input type="submit" value="Return">
            </form></td>
    </tr>
{% endfor %}
        {% include "pagination.html" %}
{% endblock %}

shop/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>

shop/templates/product_add.html
{% extends "base.html" %}

{% block title %} Add product {% endblock %}

{% block content %}
<form method="post" action="{% url 'shop:add_product' %}" enctype="multipart/form-data">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Create">
</form>
{% endblock %}

shop/templates/product_list.html
{% extends "base.html" %}
{% load static %}
{% block title %} Product list {% endblock %}

{% block content %}
    {% include "user.html" %}
<h2>Product list</h2>
    <table border="1">
    <tr>
        <td>Name</td>
        <td>Amount</td>
        <td>Cost per unit</td>
        <td>Photo</td>
    </tr>
{% for elem in object_list %}
    <tr>
        <td>{{ elem.name }}</td>
        <td>{{ elem.amount }}</td>
        <td>{{ elem.cost }}</td>
        <td><img src="{% if elem.photo %}{{ elem.photo.url}}{% else %}{% static "products/no_image.png" %}{% endif %}" width="150">
        </td>
    {% if request.user.is_superuser %}
    <td><a href="{% url 'shop:update_product' elem.id %}">Update</a></td>
    {% else %}
        {% if request.user.is_authenticated %}
        <td><form method="post" action="{% url 'shop:create_order' %}" onsubmit="return validateOrder(this)">
            {% csrf_token %}
            {{ empty_form.as_p }}
            <input name="product" type="hidden" value="{{ elem.id }}">
            <input name="user" type="hidden" value="{{ request.user.id }}">
            <input type="submit" value="Buy">
        </form></td>
            {% endif %}
    {% endif %}
    </tr>
{% endfor %}
    </table>
{% include "pagination.html" %}
{% endblock %}

shop/templates/product_update.html
{% extends "base.html" %}

{% block title %} Update product {% endblock %}

{% block content %}
<form method="post" action="{% url 'shop:update_product' object.id %}" enctype="multipart/form-data">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="update">
</form>
{% endblock %}

shop/templates/return_approved.html
{% extends "base.html" %}

{% block title %} Return approved {% endblock %}

{% block content %}
    {% include "user.html" %}
<h2>Return were successfully approved</h2>
{% endblock %}

shop/templates/return_list.html
{% extends "base.html" %}
{% block title %} Return list {% endblock %}

{% block content %}
    {% include "user.html" %}
<h2>Return list</h2>
    <form method="post" action="{% url 'shop:approve_all_returns' %}">
    <input type="submit" value="Approve all">
    {% csrf_token %}
    </form>
    <table border="1">
    <tr>
        <td>Order</td>
        <td>Date</td>
        <td>Client</td>
    </tr>
{% for elem in object_list %}
    <tr>
        <td>{{ elem.order }}</td>
        <td>{{ elem.create_date }}</td>
        <td>{{ elem.order.user }}</td>
        <td><form method="post" action="{% url 'shop:delete_return' elem.id %}">
        {% csrf_token %}
        <input name="return" type="hidden" value="{{ elem.id }}">
            <input name="approve" value="approve" type="hidden">
        <input type="submit" value="Approve">
        </form></td>
        <td><form method="post" action="{% url 'shop:delete_return' elem.id %}">
        {% csrf_token %}
        <input name="return" type="hidden" value="{{ elem.id }}">
        <input type="submit" value="Discard">
        </form></td>
    </tr>
{% endfor %}
    {% include "pagination.html" %}
{% endblock %}

shop/templates/return_success.html
{% extends "base.html" %}

{% block title %} Return success {% endblock %}

{% block content %}
    <h2>Return success</h2>
<a href="{% url 'shop:product_list' %}">Product list</a>
<a href="{% url 'shop:orders' %}">Order list</a>
{% endblock %}