djangoShop/urls.py
from django.contrib import admin
from rest_framework.authtoken import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.views import RedirectToMainView
from rest.views import CustomAuthToken

urlpatterns = [
    path("myuser/", include("myuser.urls", namespace="myuser")),
    path('admin/', admin.site.urls),
    path("shop/", include("shop.urls", namespace="shop")),
    path("rest/", include("rest.urls")),
    path('api-etoken-auth/', CustomAuthToken.as_view()),
    path("", RedirectToMainView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myuser/urls.py
from django.urls import path
from .views import Login, Logout, Register


app_name = "myuser"


urlpatterns = [
    path("login", Login.as_view(), name="login"),
    path("logout", Logout.as_view(), name="logout"),
    path("register", Register.as_view(), name="register"),
]

rest/urls.py
from .API.resources import ProductViewSet, OrderViewSet, ReturnViewSet
from rest_framework import routers


router = routers.SimpleRouter()
router.register(r'products', ProductViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'returns', ReturnViewSet)
urlpatterns = router.urls

shop/urls.py
from django.urls import path
from .views import ProductList, MainView, OrderList, ReturnSuccessView, \
    UpdateProductView, ReturnList, CreateProductView, CreateOrder, CreateReturn, DeleteReturn, CeleryReturnView


app_name = "shop"

urlpatterns = [
    path("main", MainView.as_view(), name="main"),
    path("product_list", ProductList.as_view(), name="product_list"),
    path("orders", OrderList.as_view(), name="orders"),
    path("return_success", ReturnSuccessView.as_view(), name="return_success"),
    path("update_product/<int:pk>", UpdateProductView.as_view(), name="update_product"),
    path("return_list", ReturnList.as_view(), name="return_list"),
    path("add_product", CreateProductView.as_view(), name="add_product"),
    path("create_order", CreateOrder.as_view(), name="create_order"),
    path("create_return", CreateReturn.as_view(), name="create_return"),
    path("delete_return/<int:pk>", DeleteReturn.as_view(), name="delete_return"),
    path("aprrove_all_returns/", CeleryReturnView.as_view(), name="approve_all_returns"),
]

myuser/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    wallet = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=10000)

    def __str__(self):
        return self.username

myuser/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import MyUser


class MyUserCreationForm(UserCreationForm):
    class Meta:
        fields = ("username", )
        model = MyUser

myuser/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.contrib.auth import login
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import MyUserCreationForm


class Login(LoginView):
    redirect_authenticated_user = True
    template_name = "login.html"


class Logout(LogoutView):
    template_name = "logged_out.html"


class Register(CreateView):
    form_class = MyUserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("shop:main")

    def form_valid(self, form):
        self.object = form.save()
        login(self.request, self.object)
        return HttpResponseRedirect(self.get_success_url())

myuser/templates/logged_out.html
{% extends "base.html" %}
{% block title %}Logout{% endblock %}
{% block content %}
<p>You have successfully logged out. <a href="{% url 'myuser:login' %}">Log in again</a> </p>
{% endblock %}

myuser/templates/login.html
{%  extends "base.html" %}
{%  block title %} Login {%  endblock %}
{% block content %}
<form method="post" action="{% url 'myuser:login' %}">
      {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Login">
</form>

{% endblock %}

myuser/templates/register.html
{%  extends "base.html" %}
{%  block title %} Register {%  endblock %}
{% block content %}
<form method="post" action="{% url 'myuser:register' %}">
      {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Register">
</form>
{% endblock %}

myuser/templates/user.html
<p>Hello {% if request.user.is_authenticated %}{{ request.user.username }}.
    You have ${{ request.user.wallet }}.
    <table border="1">
        <tr>
            <td><a href="{% url 'myuser:logout' %}">Logout</a></td>
            <td><a href="{% url 'shop:product_list' %}">Product list</a></td>
            <td><a href="{% url 'shop:orders' %}">Orders</a></td>
            {% if request.user.is_superuser %}
                <td><a href="{% url 'shop:return_list' %}">Returns</a></td>
                <td><a href="{% url 'shop:add_product' %}">Add product</a></td>
             {% endif %}
        </tr>
    </table>
    {% else %}Anonymous user. <a href="{% url 'myuser:login' %}">Please log in</a>
    {% endif %}
<hr>
</p>